version: '3.8'

services:
  api:
    container_name: "api-beers"
    build: ./api
    ports:
      - "80:5000"
    depends_on:
      - db
    links:
      - db

  db:
    container_name: "db-beers"
    build: ./sql
    restart: always
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: "${admin}"
      MYSQL_DATABASE: "${database}"